### ISSUE TITLE
Does the gem work with subdomains?

### ISSUE THREAD

**Issue by jlfenaux** [francesc/rails-translate-routes#12]
If I create two identical routes on two subdomains, only the first route is taken into account. 
It works as if the subdomain constraint didn't exist.

ex :

``` ruby
  constraints(:subdomain => 'foo') do
    match '/' => 'home#foo', :as => :root
  end

  constraints(:subdomain => 'bar') do
    match '/' => 'home#bar', :as => :bar_home
  end
```

bar.website.com/ points to home#foo.

**Comment by jlfenaux** [comment]
I think I found the problem. 
The subdomain is not passed to the translated routes by your gem. You deal with the request_method but not the subdomain. 

I've never created or updated gems, so I'm unable to present you with a pull request. 

Here's what I've done to make it work.
In the translate_route method, after 
`conditions[:request_method] = parse_request_methods route.verb if route.verb != //`

I added
`conditions[:subdomain] = route.constraints[:subdomain] if route.constraints`

Thanks

**Comment by francesc** [comment]
Hi,

Thanks, just released a new version of the gem with your patch. I also included you in the contributors list. :)

**Comment by jlfenaux** [comment]
Thanks ;-)

**Comment by petrachi** [comment]
Hi, 

Why in the translate_route method, the constraints on the route are only added if Rails.version >= '3.2' ?
I'm currently working on Rails 3.1 and using subdomain constraint.

**Comment by petrachi** [comment]
I have found a way to do the same in rails 3.1 (since routes.constraints is Rails >= 3.2) doing like that : 
conditions[:subdomain] = route.requirements[:subdomain] if route.requirements

I don't know for sure if 'requirements' is the same as 'constraints' but it works for me (I only use :suddomain constraint right now)

Do you want me to do a pull request with that change ?

**Comment by petrachi** [comment]
More info on the "requirements" (for you to check if it's the same as Rails 3.2 constraints) : 

If I have this simple route file : 

``` ruby
# -*- encoding : utf-8 -*-
MyApp::Application.routes.draw do
  scope :module => :www do
    constraints :subdomain => 'www' do
      match "show_me" => "route#show", :as => :show_me
      root :to => "route#index"
    end
  end

  scope :module => :lms do
    constraints :subdomain => "lms" do
      match "show_me" => "route#detail", :as => :show_me
      root :to => "route#index"
    end
  end
end

ActionDispatch::Routing::Translator.translate_from_file('config/locales/routes.yml', :prefix_on_default_locale => true)
```

(I have two controllers named 'route' who have 'index' and 'show' methods for the one living in 'www' folder, and 'index' and 'detail' methods for the one living in the 'lms' folder)

With two locales, :en and :fr, I can puts the requierements for each route : 

```
"path_info /en/show_me(.:format) -> requirements is {:action=>\"show\", :subdomain=>\"www\", :controller=>\"www/route\"}"
"path_info /fr/show_me(.:format) -> requirements is {:action=>\"show\", :subdomain=>\"www\", :controller=>\"www/route\"}"
"path_info /en -> requirements is {:action=>\"index\", :subdomain=>\"www\", :controller=>\"www/route\"}"
"path_info /fr -> requirements is {:action=>\"index\", :subdomain=>\"www\", :controller=>\"www/route\"}"
"path_info /en/show_me(.:format) -> requirements is {:action=>\"detail\", :subdomain=>\"lms\", :controller=>\"lms/route\"}"
"path_info /fr/show_me(.:format) -> requirements is {:action=>\"detail\", :subdomain=>\"lms\", :controller=>\"lms/route\"}"
"path_info /en -> requirements is {:action=>\"index\", :subdomain=>\"lms\", :controller=>\"lms/route\"}"
"path_info /fr -> requirements is {:action=>\"index\", :subdomain=>\"lms\", :controller=>\"lms/route\"}"
```

---

PS : I have noted that the constraint part in translate_route and in untranslated_route are different, is it supposed to be ?
