### ISSUE TITLE
link_to with default_url_options generates wrong URL

### ISSUE THREAD

**Issue by K-Yo** [francesc/rails-translate-routes#15]
With rails 3.2 some links are not properly generated.

To reproduce :

use the rails-translate-routes gem :
in **Gemfile**

```
gem 'rails-translate-routes'
```

in **app/views/welcome/index.html.erb**

```
<%= link_to 'working', { :controller => "welcome", :action => "index", :locale => "en" } %>
<%= link_to 'not working', { :controller => "welcome", :action => "index" } %>
<%= link_to 'working', welcome_index_path %>
```

in **app/controllers/application_controller.rb**

```
def self.default_url_options
  { :locale => I18n.locale }
end
```

this renders

```
<a href="/welcome/index">working</a>
<a href="/assets?controller=welcome&locale=en">not working</a>
<a href="/welcome/index">working</a>
```

**Comment by francesc** [comment]
Sorry you have to use the param locale for now when giving a controller and action. If somebody submits an improvement I'll look into it.
