### ISSUE TITLE
When translations are enabled url_for generates different URLs

### ISSUE THREAD

**Issue by szimek** [francesc/rails-translate-routes#20]
I'm using high_voltage gem that provides the following route:

``` ruby
match "/pages/:id", to: "high_voltage#show", as: "pages"
```

I also have my own routes to make some URLs prettier:

``` ruby
get "/faq", to: "high_voltage#show", id: "faq"
```

Without route translations, when I'm on page `/faq`, `url_for(locale: :de)` generates `/faq?locale=de`. When I enable route translations it generates `/pages/faq?locale=de` instead. 

Any idea why translating routes changes result of `url_for`?

**Comment by francesc** [comment]
I use a different approach for static pages in combination with translated routes, let me know if your interested on it.
