### ISSUE TITLE
Having routes.yml in config/locales/ potentially interferes with other translations/dictionaries

### ISSUE THREAD

**Issue by GSI** [francesc/rails-translate-routes#22]
Consider this contact.de.yml (Github formatting?):

  de:
    contact:
      form:
        h2: Schreib uns!

... and these lines in config/locales/routes.yml (Github formatting?):

de:
  contact: kontakt

Result: translation missing upon trying to get de.contact.form.h2, because de.confact now is the final definition in the chain.

I have prepared a PR with all paths changed to config/routes.yml

**Comment by francesc** [comment]
Will make a new release in a few hours to avoid the collision bug with another solution, I want translations to stay in /locales/ ;)

**Comment by GSI** [comment]
Good approach.
