### ISSUE TITLE
Using with RSpec 2

### ISSUE THREAD

**Issue by romatr** [francesc/rails-translate-routes#5]
How can I use it with RSpec 2. Controller test like

get :index
response.should be_success

return errors 'No route matches'

In routing test I'm able to test only route helpers like contact_us_en_path, but not contact_us_path

Thank you.

**Comment by francesc** [comment]
Hi,

I'm not using RSpec so I won't be able to help you at all. Sorry.

But I think the routing test helper issue is because how contact_us_path is generated, it's not a real one itself but an alias for the current language one:

```
# Add standard route helpers for default locale e.g.
#   I18n.locale = :de
#   people_path -> people_de_path
#   I18n.locale = :fr
#   people_path -> people_fr_path
def add_untranslated_helpers_to_controllers_and_views old_name
  ['path', 'url'].map do |suffix|
    new_helper_name = "#{old_name}_#{suffix}"

    ROUTE_HELPER_CONTAINER.each do |helper_container|
      helper_container.send :define_method, new_helper_name do |*args|
        send "#{old_name}_#{locale_suffix(I18n.locale)}_#{suffix}", *args
      end
    end

    new_helper_name.to_sym
  end
end
```

**Comment by cawel** [comment]
@romatr Once you translate all your routes with the rails-translate-routes gem (i.e. calling the `ActionDispatch::Routing::Translator.translate_from_file` method), all routes in your tests will need a locale. So you could do that in your controller spec:

```
get :index, :locale => 'en'
```

Hope this helps.

**Comment by romatr** [comment]
I've tried your patch and found my controller specs working now. Thank you cawel. And thank you  francesc for supporting this gem.
